//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(QuickAccessKeywords.CLASS_NAME, typeof(QuickAccessKeywords))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type QuickAccessKeywords.
    /// </summary>
    public partial class QuickAccessKeywords : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "search.quickAccessKeywords";


        /// <summary>
        /// The instance of the class that provides extended API for working with QuickAccessKeywords fields.
        /// </summary>
        private readonly QuickAccessKeywordsFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// QuickAccessKeywordsID.
        /// </summary>
        [DatabaseIDField]
        public int QuickAccessKeywordsID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("QuickAccessKeywordsID"), 0);
            }
            set
            {
                SetValue("QuickAccessKeywordsID", value);
            }
        }


        /// <summary>
        /// Keyword(s).
        /// </summary>
        [DatabaseField]
        public string Keywords
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Keywords"), "");
            }
            set
            {
                SetValue("Keywords", value);
            }
        }


        /// <summary>
        /// LinkedPage.
        /// </summary>
        [DatabaseField]
        public string LinkedPage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkedPage"), "");
            }
            set
            {
                SetValue("LinkedPage", value);
            }
        }


        /// <summary>
        /// Macro Condition.
        /// </summary>
        [DatabaseField]
        public string MacroCondition
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MacroCondition"), "");
            }
            set
            {
                SetValue("MacroCondition", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with QuickAccessKeywords fields.
        /// </summary>
        public QuickAccessKeywordsFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with QuickAccessKeywords fields.
        /// </summary>
        public partial class QuickAccessKeywordsFields
        {
            /// <summary>
            /// The content item of type QuickAccessKeywords that is a target of the extended API.
            /// </summary>
            private readonly QuickAccessKeywords mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="QuickAccessKeywordsFields" /> class with the specified content item of type QuickAccessKeywords.
            /// </summary>
            /// <param name="instance">The content item of type QuickAccessKeywords that is a target of the extended API.</param>
            public QuickAccessKeywordsFields(QuickAccessKeywords instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// QuickAccessKeywordsID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.QuickAccessKeywordsID;
                }
                set
                {
                    mInstance.QuickAccessKeywordsID = value;
                }
            }


            /// <summary>
            /// Keyword(s).
            /// </summary>
            public string Keywords
            {
                get
                {
                    return mInstance.Keywords;
                }
                set
                {
                    mInstance.Keywords = value;
                }
            }


            /// <summary>
            /// LinkedPage.
            /// </summary>
            public string LinkedPage
            {
                get
                {
                    return mInstance.LinkedPage;
                }
                set
                {
                    mInstance.LinkedPage = value;
                }
            }


            /// <summary>
            /// Macro Condition.
            /// </summary>
            public string MacroCondition
            {
                get
                {
                    return mInstance.MacroCondition;
                }
                set
                {
                    mInstance.MacroCondition = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="QuickAccessKeywords" /> class.
        /// </summary>
        public QuickAccessKeywords() : base(CLASS_NAME)
        {
            mFields = new QuickAccessKeywordsFields(this);
        }

        #endregion
    }
}