//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CMSWebParts_Chat_ChatRooms {
    
    /// <summary>
    /// pnlChatRooms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRooms;
    
    /// <summary>
    /// pnlChatRoomsFiltering control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsFiltering;
    
    /// <summary>
    /// txtChatRoomsFilter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsFilter;
    
    /// <summary>
    /// btnChatRoomsFilter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsFilter;
    
    /// <summary>
    /// pnlChatRoomsInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsInfo;
    
    /// <summary>
    /// pnlChatRoomsPaging control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsPaging;
    
    /// <summary>
    /// pnlChatRoomsList control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsList;
    
    /// <summary>
    /// pnlChatRoomsCreateRoom control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsCreateRoom;
    
    /// <summary>
    /// btnChatRoomsCreateRoom control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsCreateRoom;
    
    /// <summary>
    /// pnlChatRoomsPrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsPrompt;
    
    /// <summary>
    /// imgChatRoomsPrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgChatRoomsPrompt;
    
    /// <summary>
    /// lblChatRoomsPromptHeader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsPromptHeader;
    
    /// <summary>
    /// lblChatRoomsPromptEnterPassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsPromptEnterPassword;
    
    /// <summary>
    /// txtChatRoomsPromptInput control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsPromptInput;
    
    /// <summary>
    /// pnlChatRoomsPromptPasswordError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsPromptPasswordError;
    
    /// <summary>
    /// btnChatRoomsPromptSubmit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsPromptSubmit;
    
    /// <summary>
    /// btnChatRoomsPromptClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsPromptClose;
    
    /// <summary>
    /// pnlChatRoomsCreatePrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsCreatePrompt;
    
    /// <summary>
    /// imgChatRoomsCreatePrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgChatRoomsCreatePrompt;
    
    /// <summary>
    /// lblChatRoomsCreateHeader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreateHeader;
    
    /// <summary>
    /// pnlChatRoomsCreateError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsCreateError;
    
    /// <summary>
    /// imgChatRoomsCreateError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgChatRoomsCreateError;
    
    /// <summary>
    /// lblChatRoomsCreateError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreateError;
    
    /// <summary>
    /// lblChatRoomsCreateName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreateName;
    
    /// <summary>
    /// txtChatRoomsCreateName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsCreateName;
    
    /// <summary>
    /// lblChatRoomsCreateDescription control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreateDescription;
    
    /// <summary>
    /// txtChatRoomsCreateDescription control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextArea txtChatRoomsCreateDescription;
    
    /// <summary>
    /// lblChatRoomsCreateAllowAnonym control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreateAllowAnonym;
    
    /// <summary>
    /// chkChatRoomsCreateAllowAnonym control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSCheckBox chkChatRoomsCreateAllowAnonym;
    
    /// <summary>
    /// lblChatRoomsCreateIsPrivate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreateIsPrivate;
    
    /// <summary>
    /// chkChatRoomsCreateIsPrivate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSCheckBox chkChatRoomsCreateIsPrivate;
    
    /// <summary>
    /// lblChatRoomsCreatePassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreatePassword;
    
    /// <summary>
    /// txtChatRoomsCreatePassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsCreatePassword;
    
    /// <summary>
    /// lblChatRoomsCreatePasswordConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsCreatePasswordConfirm;
    
    /// <summary>
    /// txtChatRoomsCreatePasswordConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsCreatePasswordConfirm;
    
    /// <summary>
    /// pnlChatRoomsCreateErrorConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsCreateErrorConfirm;
    
    /// <summary>
    /// btnChatRoomsCreatePromptSubmit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsCreatePromptSubmit;
    
    /// <summary>
    /// btnChatRoomsCreatePromptClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsCreatePromptClose;
    
    /// <summary>
    /// pnlChatRoomsDeletePrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsDeletePrompt;
    
    /// <summary>
    /// imgChatRoomsDeletePrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgChatRoomsDeletePrompt;
    
    /// <summary>
    /// lblChatRoomsDeleteHeader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsDeleteHeader;
    
    /// <summary>
    /// lblChatRoomsDeletePromptConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsDeletePromptConfirm;
    
    /// <summary>
    /// btnChatRoomsDeletePromptSubmit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsDeletePromptSubmit;
    
    /// <summary>
    /// btnChatRoomsDeletePromptClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsDeletePromptClose;
    
    /// <summary>
    /// pnlChatRoomsAbandonPrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsAbandonPrompt;
    
    /// <summary>
    /// imgChatRoomsAbandonPrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgChatRoomsAbandonPrompt;
    
    /// <summary>
    /// lblChatRoomsAbandonHeader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsAbandonHeader;
    
    /// <summary>
    /// lblChatRoomsAbandonPromptConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsAbandonPromptConfirm;
    
    /// <summary>
    /// btnChatRoomsAbandonPromptSubmit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsAbandonPromptSubmit;
    
    /// <summary>
    /// btnChatRoomsAbandonPromptClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsAbandonPromptClose;
    
    /// <summary>
    /// pnlChatRoomsEditPrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsEditPrompt;
    
    /// <summary>
    /// imgChatRoomsEditPrompt control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgChatRoomsEditPrompt;
    
    /// <summary>
    /// lblChatRoomsEditHeader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditHeader;
    
    /// <summary>
    /// pnlChatRoomsEditError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsEditError;
    
    /// <summary>
    /// imgChatRoomsEditError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Image imgChatRoomsEditError;
    
    /// <summary>
    /// lblChatRoomsEditError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditError;
    
    /// <summary>
    /// lblChatRoomsEditName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditName;
    
    /// <summary>
    /// txtChatRoomsEditName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsEditName;
    
    /// <summary>
    /// lblChatRoomsEditDescription control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditDescription;
    
    /// <summary>
    /// txtChatRoomsEditDescription control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextArea txtChatRoomsEditDescription;
    
    /// <summary>
    /// lblChatRoomsEditAllowAnonym control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditAllowAnonym;
    
    /// <summary>
    /// chkChatRoomsEditAllowAnonym control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSCheckBox chkChatRoomsEditAllowAnonym;
    
    /// <summary>
    /// lblChatRoomsEditIsPrivate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditIsPrivate;
    
    /// <summary>
    /// chkChatRoomsEditIsPrivate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSCheckBox chkChatRoomsEditIsPrivate;
    
    /// <summary>
    /// lblChatRoomsHasPassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsHasPassword;
    
    /// <summary>
    /// chkChatRoomsHasPassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSCheckBox chkChatRoomsHasPassword;
    
    /// <summary>
    /// lblChatRoomsEditPasswordNew control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditPasswordNew;
    
    /// <summary>
    /// txtChatRoomsEditPassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsEditPassword;
    
    /// <summary>
    /// lblChatRoomsEditPasswordConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedLabel lblChatRoomsEditPasswordConfirm;
    
    /// <summary>
    /// txtChatRoomsEditPasswordConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.CMSTextBox txtChatRoomsEditPasswordConfirm;
    
    /// <summary>
    /// pnlChatRoomsEditErrorConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatRoomsEditErrorConfirm;
    
    /// <summary>
    /// btnChatRoomsEditPromptSubmit control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsEditPromptSubmit;
    
    /// <summary>
    /// btnChatRoomsEditPromptClose control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.ExtendedControls.LocalizedButton btnChatRoomsEditPromptClose;
}
