//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(JobListing.CLASS_NAME, typeof(JobListing))]

namespace CMS.DocumentEngine.Types
{
    /// <summary>
    /// Represents a content item of type JobListing.
    /// </summary>
    public partial class JobListing : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "jobs.jobListing";


        /// <summary>
        /// The instance of the class that provides extended API for working with JobListing fields.
        /// </summary>
        private readonly JobListingFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// JobListingID.
        /// </summary>
        [DatabaseIDField]
        public int JobListingID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("JobListingID"), 0);
            }
            set
            {
                SetValue("JobListingID", value);
            }
        }


        /// <summary>
        /// Job Title.
        /// </summary>
        [DatabaseField]
        public string JobTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobTitle"), "");
            }
            set
            {
                SetValue("JobTitle", value);
            }
        }


        /// <summary>
        /// Job Location.
        /// </summary>
        [DatabaseField]
        public int JobCampusID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("JobCampusID"), 1);
            }
            set
            {
                SetValue("JobCampusID", value);
            }
        }


        /// <summary>
        /// Direct Report.
        /// </summary>
        [DatabaseField]
        public string DirectReport
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DirectReport"), "");
            }
            set
            {
                SetValue("DirectReport", value);
            }
        }


        /// <summary>
        /// Employment Status.
        /// </summary>
        [DatabaseField]
        public string JobEmploymentStatus
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobEmploymentStatus"), "Part-time");
            }
            set
            {
                SetValue("JobEmploymentStatus", value);
            }
        }


        /// <summary>
        /// Position Summary.
        /// </summary>
        [DatabaseField]
        public string JobSummary
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobSummary"), "");
            }
            set
            {
                SetValue("JobSummary", value);
            }
        }


        /// <summary>
        /// Job Responsibilities.
        /// </summary>
        [DatabaseField]
        public string JobResponsibilities
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobResponsibilities"), "");

            }
            set
            {
                SetValue("JobResponsibilities", value);
            }
        }


        /// <summary>
        /// Qualifications & Requirements.
        /// </summary>
        [DatabaseField]
        public string JobQualifications
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobQualifications"), "");

            }
            set
            {
                SetValue("JobQualifications", value);
            }
        }


        /// <summary>
        /// Personal/Character.
        /// </summary>
        [DatabaseField]
        public string JobCharacter
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobCharacter"), "");

            }
            set
            {
                SetValue("JobCharacter", value);
            }
        }


        /// <summary>
        /// Application URL.
        /// </summary>
        [DatabaseField]
        public string JobApplicationUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("JobApplicationUrl"), "/employment/application");
            }
            set
            {
                SetValue("JobApplicationUrl", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with JobListing fields.
        /// </summary>
        public JobListingFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with JobListing fields.
        /// </summary>
        public partial class JobListingFields
        {
            /// <summary>
            /// The content item of type JobListing that is a target of the extended API.
            /// </summary>
            private readonly JobListing mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="JobListingFields" /> class with the specified content item of type JobListing.
            /// </summary>
            /// <param name="instance">The content item of type JobListing that is a target of the extended API.</param>
            public JobListingFields(JobListing instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// JobListingID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.JobListingID;
                }
                set
                {
                    mInstance.JobListingID = value;
                }
            }


            /// <summary>
            /// Job Title.
            /// </summary>
            public string JobTitle
            {
                get
                {
                    return mInstance.JobTitle;
                }
                set
                {
                    mInstance.JobTitle = value;
                }
            }


            /// <summary>
            /// Job Location.
            /// </summary>
            public int JobCampusID
            {
                get
                {
                    return mInstance.JobCampusID;
                }
                set
                {
                    mInstance.JobCampusID = value;
                }
            }


            /// <summary>
            /// Direct Report.
            /// </summary>
            public string DirectReport
            {
                get
                {
                    return mInstance.DirectReport;
                }
                set
                {
                    mInstance.DirectReport = value;
                }
            }


            /// <summary>
            /// Employment Status.
            /// </summary>
            public string JobEmploymentStatus
            {
                get
                {
                    return mInstance.JobEmploymentStatus;
                }
                set
                {
                    mInstance.JobEmploymentStatus = value;
                }
            }


            /// <summary>
            /// Position Summary.
            /// </summary>
            public string JobSummary
            {
                get
                {
                    return mInstance.JobSummary;
                }
                set
                {
                    mInstance.JobSummary = value;
                }
            }


            /// <summary>
            /// Job Responsibilities.
            /// </summary>
            public string JobResponsibilities
            {
                get
                {
                    return mInstance.JobResponsibilities;
                }
                set
                {
                    mInstance.JobResponsibilities = value;
                }
            }


            /// <summary>
            /// Qualifications & Requirements.
            /// </summary>
            public string JobQualifications
            {
                get
                {
                    return mInstance.JobQualifications;
                }
                set
                {
                    mInstance.JobQualifications = value;
                }
            }


            /// <summary>
            /// Personal/Character.
            /// </summary>
            public string JobCharacter
            {
                get
                {
                    return mInstance.JobCharacter;
                }
                set
                {
                    mInstance.JobCharacter = value;
                }
            }


            /// <summary>
            /// Application URL.
            /// </summary>
            public string JobApplicationUrl
            {
                get
                {
                    return mInstance.JobApplicationUrl;
                }
                set
                {
                    mInstance.JobApplicationUrl = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="JobListing" /> class.
        /// </summary>
        public JobListing() : base(CLASS_NAME)
        {
            mFields = new JobListingFields(this);
        }

        #endregion
    }
}